name: Deploy Frontend from ECR

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::195275652706:role/github-actions-role
          aws-region: ap-northeast-2

      - name: Build & Push Docker image
        run: |
          docker build -t frontend .
          docker tag frontend:latest 195275652706.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 195275652706.dkr.ecr.ap-northeast-2.amazonaws.com
          docker push 195275652706.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest

      - name: Trigger CodeDeploy with AppSpecContent
        run: |
          aws deploy create-deployment \
            --application-name Jeff-app \
            --deployment-group-name frontend-group \
            --revision '{"revisionType":"AppSpecContent","appSpecContent":{"content":"'"$(base64 appspec.yml)"'","sha256":"'"$(openssl dgst -sha256 -binary appspec.yml | openssl base64)"'"}}' \
            --deployment-config-name CodeDeployDefault.OneAtATime
